package com.tuya.spongycastle.asn1.x9;

import com.tuya.smart.common.OO000o0;
import com.tuya.smart.common.oOO0O0O0;
import com.tuya.spongycastle.asn1.ASN1ObjectIdentifier;

public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier ansi_X9_42;
    public static final ASN1ObjectIdentifier ansi_X9_62;
    public static final ASN1ObjectIdentifier c2onb191v4 = cTwoCurve.branch("8");
    public static final ASN1ObjectIdentifier c2onb191v5 = cTwoCurve.branch("9");
    public static final ASN1ObjectIdentifier c2onb239v4 = cTwoCurve.branch("14");
    public static final ASN1ObjectIdentifier c2onb239v5 = cTwoCurve.branch("15");
    public static final ASN1ObjectIdentifier c2pnb163v1;
    public static final ASN1ObjectIdentifier c2pnb163v2 = cTwoCurve.branch("2");
    public static final ASN1ObjectIdentifier c2pnb163v3 = cTwoCurve.branch(OO000o0.O00000o);
    public static final ASN1ObjectIdentifier c2pnb176w1 = cTwoCurve.branch(OO000o0.O00000o0);
    public static final ASN1ObjectIdentifier c2pnb208w1 = cTwoCurve.branch("10");
    public static final ASN1ObjectIdentifier c2pnb272w1 = cTwoCurve.branch("16");
    public static final ASN1ObjectIdentifier c2pnb304w1 = cTwoCurve.branch("17");
    public static final ASN1ObjectIdentifier c2pnb368w1 = cTwoCurve.branch("19");
    public static final ASN1ObjectIdentifier c2tnb191v1 = cTwoCurve.branch("5");
    public static final ASN1ObjectIdentifier c2tnb191v2 = cTwoCurve.branch("6");
    public static final ASN1ObjectIdentifier c2tnb191v3 = cTwoCurve.branch("7");
    public static final ASN1ObjectIdentifier c2tnb239v1 = cTwoCurve.branch("11");
    public static final ASN1ObjectIdentifier c2tnb239v2 = cTwoCurve.branch("12");
    public static final ASN1ObjectIdentifier c2tnb239v3 = cTwoCurve.branch("13");
    public static final ASN1ObjectIdentifier c2tnb359v1 = cTwoCurve.branch("18");
    public static final ASN1ObjectIdentifier c2tnb431r1 = cTwoCurve.branch("20");
    public static final ASN1ObjectIdentifier cTwoCurve;
    public static final ASN1ObjectIdentifier characteristic_two_field;
    public static final ASN1ObjectIdentifier dhEphem = x9_42_schemes.branch("2");
    public static final ASN1ObjectIdentifier dhHybrid1 = x9_42_schemes.branch(OO000o0.O00000o0);
    public static final ASN1ObjectIdentifier dhHybrid2 = x9_42_schemes.branch("5");
    public static final ASN1ObjectIdentifier dhHybridOneFlow = x9_42_schemes.branch("6");
    public static final ASN1ObjectIdentifier dhOneFlow = x9_42_schemes.branch(OO000o0.O00000o);
    public static final ASN1ObjectIdentifier dhSinglePass_cofactorDH_sha1kdf_scheme = x9_63_scheme.branch(OO000o0.O00000o);
    public static final ASN1ObjectIdentifier dhSinglePass_stdDH_sha1kdf_scheme;
    public static final ASN1ObjectIdentifier dhStatic;
    public static final ASN1ObjectIdentifier dhpublicnumber;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA1;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA2;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA224;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA256 = ecdsa_with_SHA2.branch("2");
    public static final ASN1ObjectIdentifier ecdsa_with_SHA384 = ecdsa_with_SHA2.branch(OO000o0.O00000o);
    public static final ASN1ObjectIdentifier ecdsa_with_SHA512 = ecdsa_with_SHA2.branch(OO000o0.O00000o0);
    public static final ASN1ObjectIdentifier ellipticCurve;
    public static final ASN1ObjectIdentifier gnBasis;
    public static final ASN1ObjectIdentifier id_dsa = new ASN1ObjectIdentifier("1.2.840.10040.4.1");
    public static final ASN1ObjectIdentifier id_dsa_with_sha1 = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
    public static final ASN1ObjectIdentifier id_ecPublicKey;
    public static final ASN1ObjectIdentifier id_ecSigType;
    public static final ASN1ObjectIdentifier id_fieldType;
    public static final ASN1ObjectIdentifier id_kdf_kdf2;
    public static final ASN1ObjectIdentifier id_kdf_kdf3 = x9_44_components.branch("2");
    public static final ASN1ObjectIdentifier id_publicKeyType;
    public static final ASN1ObjectIdentifier mqv1 = x9_42_schemes.branch("8");
    public static final ASN1ObjectIdentifier mqv2 = x9_42_schemes.branch("7");
    public static final ASN1ObjectIdentifier mqvSinglePass_sha1kdf_scheme = x9_63_scheme.branch("16");
    public static final ASN1ObjectIdentifier ppBasis = characteristic_two_field.branch("3.3");
    public static final ASN1ObjectIdentifier prime192v1;
    public static final ASN1ObjectIdentifier prime192v2 = primeCurve.branch("2");
    public static final ASN1ObjectIdentifier prime192v3 = primeCurve.branch(OO000o0.O00000o);
    public static final ASN1ObjectIdentifier prime239v1 = primeCurve.branch(OO000o0.O00000o0);
    public static final ASN1ObjectIdentifier prime239v2 = primeCurve.branch("5");
    public static final ASN1ObjectIdentifier prime239v3 = primeCurve.branch("6");
    public static final ASN1ObjectIdentifier prime256v1 = primeCurve.branch("7");
    public static final ASN1ObjectIdentifier primeCurve;
    public static final ASN1ObjectIdentifier prime_field;
    public static final ASN1ObjectIdentifier tpBasis = characteristic_two_field.branch("3.2");
    public static final ASN1ObjectIdentifier x9_42_schemes;
    public static final ASN1ObjectIdentifier x9_44;
    public static final ASN1ObjectIdentifier x9_44_components;
    public static final ASN1ObjectIdentifier x9_63_scheme;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        ansi_X9_62 = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier branch = aSN1ObjectIdentifier.branch("1");
        id_fieldType = branch;
        prime_field = branch.branch("1");
        ASN1ObjectIdentifier branch2 = id_fieldType.branch("2");
        characteristic_two_field = branch2;
        gnBasis = branch2.branch("3.1");
        ASN1ObjectIdentifier branch3 = ansi_X9_62.branch(OO000o0.O00000o0);
        id_ecSigType = branch3;
        ecdsa_with_SHA1 = branch3.branch("1");
        ASN1ObjectIdentifier branch4 = ansi_X9_62.branch("2");
        id_publicKeyType = branch4;
        id_ecPublicKey = branch4.branch("1");
        ASN1ObjectIdentifier branch5 = id_ecSigType.branch(OO000o0.O00000o);
        ecdsa_with_SHA2 = branch5;
        ecdsa_with_SHA224 = branch5.branch("1");
        ASN1ObjectIdentifier branch6 = ansi_X9_62.branch(OO000o0.O00000o);
        ellipticCurve = branch6;
        ASN1ObjectIdentifier branch7 = branch6.branch(oOO0O0O0.O0000oO0);
        cTwoCurve = branch7;
        c2pnb163v1 = branch7.branch("1");
        ASN1ObjectIdentifier branch8 = ellipticCurve.branch("1");
        primeCurve = branch8;
        prime192v1 = branch8.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        x9_63_scheme = aSN1ObjectIdentifier2;
        dhSinglePass_stdDH_sha1kdf_scheme = aSN1ObjectIdentifier2.branch("2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.10046");
        ansi_X9_42 = aSN1ObjectIdentifier3;
        dhpublicnumber = aSN1ObjectIdentifier3.branch("2.1");
        ASN1ObjectIdentifier branch9 = ansi_X9_42.branch(OO000o0.O00000o);
        x9_42_schemes = branch9;
        dhStatic = branch9.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        x9_44 = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier branch10 = aSN1ObjectIdentifier4.branch("1");
        x9_44_components = branch10;
        id_kdf_kdf2 = branch10.branch("1");
    }
}
